### ISSUE TITLE
latexify does not support objects of type typeof(min)?

### ISSUE THREAD

**Issue by briochemc** [korsbo/Latexify.jl#131] opened 2020-12-11 08:01 UTC
Using Catalyst, I stumbled upon this error. Not sure why since `latexify` works fine with, e.g., `latexify( :( min(a,b) ) )`. 

MWE:

```julia
julia> using Catalyst

julia> rn = @reaction_network begin
           min(a,b), 0 --> Z
       end a b
ReactionSystem(Reaction[Reaction{Any,Int64}(min(a, b), Term[], Term{Real}[Z(t)], Int64[], [1], Pair{Any,Int64}[Z(t) => 1], false)], t, Term{Real}[Z(t)], Sym{ModelingToolkit.Parameter{Real}}[a, b], Any[], Equation[], Symbol("##ReactionSystem#254"), ReactionSystem[])

julia> latexify(rn)
ERROR: AssertionError: latexify does not support objects of type typeof(min).
```

But maybe this should be raised on Catalyst.jl?

---

Full stack trace FWIW:

```julia
ERROR: AssertionError: latexify does not support objects of type typeof(min).
Stacktrace:
 [1] #latexraw#7(kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:convert_unicode, :env),Tuple{Bool,Symbol}}}, ::typeof(latexraw), args...::Function)
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexraw.jl:89

 [2] #22(i::Function)
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexoperation.jl:11

 [3] iterate
   @ /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../share/julia/base/generator.jl:47 [inlined]

 [4] _collect(c::Array{Any,1}, itr::Base.Generator{Array{Any,1},Latexify.var"#22#25"{Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:convert_unicode, :env),Tuple{Bool,Symbol}}}}}, ::Base.EltypeUnknown, isz::Base.HasShape{1})
   @ Base /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../share/julia/base/array.jl:699

 [5] collect_similar
   @ Base /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../share/julia/base/array.jl:628 [inlined]

 [6] map
   @ /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../share/julia/base/abstractarray.jl:2162 [inlined]

 [7] #latexoperation#21(cdot::Bool, index::Symbol, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:convert_unicode, :env),Tuple{Bool,Symbol}}}, ::typeof(Latexify.latexoperation), ex::Expr, prevOp::Array{Symbol,1})
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexoperation.jl:11

 [8] recurseexp!(ex::Expr)
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexraw.jl:79

 [9] #latexraw#3(convert_unicode::Bool, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:cdot, :env),Tuple{Bool,Symbol}}}, ::typeof(latexraw), inputex::Expr)
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexraw.jl:82

[10] #chemical_arrows#36(expand::Bool, double_linebreak::Bool, mathjax::Bool, starred::Bool, kwargs::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:cdot, :env),Tuple{Bool,Symbol}}}, ::typeof(Catalyst.chemical_arrows), rn::ReactionSystem)
   @ Catalyst ~/.julia/packages/Catalyst/EYzVj/src/latexify_recipes.jl:93

[11] #latexify#29(kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(latexify), args...::ReactionSystem)
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexify_function.jl:11

[12] latexify(args...::ReactionSystem)
   @ Latexify ~/.julia/packages/Latexify/gaIt2/src/latexify_function.jl:4

[13] top-level scope
   @ REPL[5]:1
```

**Comment by korsbo** [comment] 2020-12-11 08:25
Such a lovely stacktrace 🙂. The issue is likely one of the Catalyst latexify recipe or of how Catalyst uses "external" functions inside its reactions. Both these things are on my list of things to rewrite this month so I'll use this as a test case then - ensuring that it gets fixed in the process.

**Comment by korsbo** [comment] 2020-12-21 08:46
Probably the same issue as https://github.com/SciML/ModelingToolkit.jl/issues/689

**Comment by ChrisRackauckas** [comment] 2020-12-21 12:43
Can you automatically call `symbol` on `<:Function`?

**Comment by korsbo** [comment] 2020-12-21 15:15
The issue was in the conversion of ModelingToolkit's equations to expressions. I'm pretty sure that https://github.com/SciML/ModelingToolkit.jl/pull/693 will solve this issue. 

We'll have to make sure that this update is pulled into Catalyst though. It seems that Catalyst locks MKT to version 4.0.1.

**Comment by korsbo** [comment] 2020-12-21 15:18
> We'll have to make sure that this update is pulled into Catalyst though. It seems that Catalyst locks MTK to version 4.0.1.

nope. That was just me misinterpreting the semver of Pkg's compat bounds. We should be all good.

**Comment by korsbo** [comment] 2020-12-22 09:18
Solved by https://github.com/SciML/ModelingToolkit.jl/pull/693. Update to ModelingToolkit v4.3.1 or higher and it should all work.

**Closed by korsbo** 2020-12-22 09:18 UTC
